apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodejs-app2
  labels:
    app: nodejs-app2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodejs-app2
  template:
    metadata:
      labels:
        app: nodejs-app2
    spec:
      containers:
      - name: nodejs-app2
        image: uphiller/nodejs-hello-world
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: hello-config
