apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-app-database
  labels:
    app: board-app-database
    group: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-app-database
  template:
    metadata:
      labels:
        app: board-app-database
        group: board
    spec:
      hostname: database
      subdomain: board
      containers:
      - name: mysql
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "1234"
        ports:
        - containerPort: 3306
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-app-front
  labels:
    app: board-app-front
    group: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-app-front
  template:
    metadata:
      labels:
        app: board-app-front
    spec:
      containers:
      - name: board-app-front
        image: yhc94/board-front
        ports:
        - containerPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: board-app-backend
  labels:
    app: board-app-backend
    group: board
spec:
  replicas: 1
  selector:
    matchLabels:
      app: board-app-backend
  template:
    metadata:
      labels:
        app: board-app-backend
    spec:
      containers:
      - name: board-app-backend
        image: yhc94/board-backend:dev
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: board
spec:
  selector:
    group: board
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: board-app-front
spec:
  type: NodePort
  selector:
    app: board-app-front
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: board-app-backend
spec:
  type: NodePort
  selector:
    app: board-app-backend
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080

