apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: board-front
    spec:
      type: NodePort
      selector:
        app: board-app
      ports:
      - port: 80
        protocol: TCP
        targetPort: 80
  - apiVersion: v1
    kind: Service
    metadata:
      name: board-backend
    spec:
      type: NodePort
      selector:
        app: board-app
      ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080
