apiVersion: v1
kind: Pod
metadata:
  name: nginx-tolerant
spec:
  containers:
  - name: nginx
    image: nginx
  tolerations:
  - key: "env"
    operator: "Equal"
    value: "test"
    effect: "NoSchedule"
